### PR TITLE
Update/rebuild navbar [fix #36]

### LINKED ISSUE #36: Navigation: refactor and simplify navbar component
+ dark variant

### PR DESCRIPTION
**Pull request by craigcook**
Reworks the nav component(s) based on current styling in bedrock, also adding dark mode support.

UPPDATE: Done. ~For dark mode we'll need to add `mzp-t-dark` to the main nav container (c-navigation) as well as to the shoulder CTA button (trying to make the button styles inherit from the ancestor got very fiddly and we have a dark mode button class already so we should use it). Assuming this should be an option in the global settings.~

### CODE REVIEW

**Comment by stevejalim** [comment]
@craigcook I've added the optons in the site settings to pick light or dark theme and we're now using it in the template - see https://github.com/mozmeao/birdbox/pull/67/commits/c94b7a3559b82a09da4d397672238ca57cfbaa3f

Screenshot 2023-09-20 at 11 51 28
Screenshot 2023-09-20 at 11 50 47

**Comment by stevejalim** [comment]
@craigcook While testing it out, I found a way to break things by adding multiple child pages to a parent page (you can replicate locally by copying and existing page and tweaking its title and slug):

Screenshot 2023-09-20 at 10 13 36


I found that after a while we got right-side runover:

Screenshot 2023-09-20 at 10 14 06


Just wondering: shall we allow things to go more than two deep in the nav? Pushing that to up to three would help us I think, and if images and desccriptions are set then it still shouldn't get too long. (Extra thought: would four-deep with descriptions and images be too tall?)

**Comment by craigcook** [comment]
Oh we definitely have to allow more than two, not sure why that's happening... mozorg has up to four with descriptions and it looks fine. I think we could allow as many as six items and if they also include descriptions that's a choice the user will have to make. The main thing is that it should only be two columns, so 12 items total.

**Comment by craigcook** [comment]
Oh I see it now... somehow I missed that `mzp-l-rows-two` class 🤦

**Review by stevejalim — APPROVED** [review]
r+ - tested locally with a lot of child pages and it holds up to sensible use

**Pull request merged**
